In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [3]:
df = pd.read_csv("bikes.csv")

df.head(15)

,model_name,model_year,kms_driven,owner,location,mileage,power,price
0,Bajaj Avenger Cruise 220 2017,2017,17000 Km,first owner,hyderabad,\n\n 35 kmpl,19 bhp,63500
1,Royal Enfield Classic 350cc 2016,2016,50000 Km,first owner,hyderabad,\n\n 35 kmpl,19.80 bhp,115000
2,Hyosung GT250R 2012,2012,14795 Km,first owner,hyderabad,\n\n 30 kmpl,28 bhp,300000
3,Bajaj Dominar 400 ABS 2017,2017,Mileage 28 Kms,first owner,pondicherry,\n\n 28 Kms,34.50 bhp,100000
4,Jawa Perak 330cc 2020,2020,2000 Km,first owner,bangalore,\n\n,30 bhp,197500
5,KTM Duke 200cc 2012,2012,24561 Km,third owner,bangalore,\n\n 35 kmpl,25 bhp,63400
6,Bajaj Pulsar 180cc 2016,2016,19718 Km,first owner,bangalore,\n\n 65 kmpl,17 bhp,55000
7,TVS Apache RTR 200 4V Dual Channel ABS BS6 2020,2020,Mileage 40 Kmpl,first owner,hyderabad,\n\n 40 Kmpl,20.21 bhp,120000
8,KTM Duke 390cc 2018,2018,1350 Km,first owner,jaipur,\n\n 25 kmpl,42.90 bhp,198000
9,Yamaha FZ16 150cc 2014,2014,Mileage 58 Kmpl,first owner,bangalore,\n\n 58 Kmpl,13 bhp,40000
10,Royal Enfield Classic 350cc 2018,2018,25000 Km,first owner,chennai,\n\n 35 kmpl,19.80 bhp,136900
11,Royal Enfield Himalayan 410cc 2016,2016,26240 Km,first owner,ghaziabad,\n\n 32 kmpl,24.50 bhp,112000
12,Royal Enfield Bullet Electra 350cc 2017,2017,18866 Km,first owner,delhi,\n\n 40 kmpl,19.8 Bhp,110000
13,Honda CB Shine 125cc 2018,2018,Mileage 65 Kmpl,first owner,delhi,\n\n 65 Kmpl,10 bhp,50000
14,Royal Enfield Standard 350cc 2019,2019,Mileage 30 Kmpl,first owner,delhi,\n\n 30 Kmpl,18 bhp,131000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7857 entries, 0 to 7856
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   model_name  7857 non-null   str
 1   model_year  7857 non-null   int64
 2   kms_driven  7857 non-null   str
 3   owner       7857 non-null   str
 4   location    7838 non-null   str
 5   mileage     7846 non-null   str
 6   power       7826 non-null   str
 7   price       7857 non-null   int64
dtypes: int64(2), str(6)
memory usage: 491.2 KB

In [5]:
df.describe()

        model_year         price
count  7857.000000  7.857000e+03
mean   2015.367698  1.067913e+05
std       4.001443  1.389261e+05
min    1950.000000  0.000000e+00
25%    2014.000000  4.200000e+04
50%    2016.000000  7.500000e+04
75%    2018.000000  1.250000e+05
max    2021.000000  3.000000e+06

In [6]:
df.isnull().sum()

model_name     0
model_year     0
kms_driven     0
owner          0
location      19
mileage       11
power         31
price          0
dtype: int64

In [8]:
# data clening
df['kms_driven'] = pd.to_numeric(df['kms_driven'].str.replace(r'[^\d]', '', regex=True),errors='coerce')

df['mileage'] = pd.to_numeric(df['mileage'].str.replace(r'[^\d]', '', regex=True),errors='coerce')

# 3. Clean power (Extract decimal or integer)
df['power'] = pd.to_numeric(
    df['power'].str.extract(r'(\d+\.?\d*)')[0],
    errors='coerce'
)

In [15]:
df.head()

,model_name,model_year,kms_driven,owner,location,mileage,power,price,bike_age
0,Bajaj Avenger Cruise 220 2017,2017,17000.0,first owner,hyderabad,35.0,19.0,63500,9
1,Royal Enfield Classic 350cc 2016,2016,50000.0,first owner,hyderabad,35.0,19.8,115000,10
2,Hyosung GT250R 2012,2012,14795.0,first owner,hyderabad,30.0,28.0,300000,14
3,Bajaj Dominar 400 ABS 2017,2017,28.0,first owner,pondicherry,28.0,34.5,100000,9
4,Jawa Perak 330cc 2020,2020,2000.0,first owner,bangalore,NaN,30.0,197500,6

In [11]:
df['location'] = df['location'].str.strip()
df['owner'] = df['owner'].str.strip().str.lower()

In [13]:
df['bike_age'] = 2026 - df['model_year']

In [14]:
df

,model_name,model_year,kms_driven,owner,location,mileage,power,price,bike_age
0,Bajaj Avenger Cruise 220 2017,2017,17000.0,first owner,hyderabad,35.0,19.0,63500,9
1,Royal Enfield Classic 350cc 2016,2016,50000.0,first owner,hyderabad,35.0,19.8,115000,10
2,Hyosung GT250R 2012,2012,14795.0,first owner,hyderabad,30.0,28.0,300000,14
3,Bajaj Dominar 400 ABS 2017,2017,28.0,first owner,pondicherry,28.0,34.5,100000,9
4,Jawa Perak 330cc 2020,2020,2000.0,first owner,bangalore,NaN,30.0,197500,6
...,...,...,...,...,...,...,...,...,...
7852,Yamaha YZF-R15 150cc 2011,2011,7000.0,first owner,agra,42.0,16.0,55000,15
7853,Bajaj Discover 100cc 2015,2015,80.0,first owner,delhi,80.0,7.7,28000,11
7854,Bajaj Pulsar 180cc 2016,2016,6407.0,first owner,bangalore,65.0,17.0,61740,10
7855,Bajaj V15 150cc 2016,2016,7524.0,first owner,bangalore,57.0,11.8,49000,10
7856,Bajaj Pulsar 220cc 2016,2016,15000.0,first owner,chennai,38.0,21.0,65000,10

In [17]:
owner_mapping = {
    'first owner': 1,
    'second Owner': 2,
    'third Owner': 3,
    'fourth Owner': 4,
    'fifth Owner': 5
}

df['owner'] = df['owner'].map(owner_mapping)

df.head()

,model_name,model_year,kms_driven,owner,location,mileage,power,price,bike_age
0,Bajaj Avenger Cruise 220 2017,2017,17000.0,1.0,hyderabad,35.0,19.0,63500,9
1,Royal Enfield Classic 350cc 2016,2016,50000.0,1.0,hyderabad,35.0,19.8,115000,10
2,Hyosung GT250R 2012,2012,14795.0,1.0,hyderabad,30.0,28.0,300000,14
3,Bajaj Dominar 400 ABS 2017,2017,28.0,1.0,pondicherry,28.0,34.5,100000,9
4,Jawa Perak 330cc 2020,2020,2000.0,1.0,bangalore,NaN,30.0,197500,6

In [18]:
numeric_cols = df.select_dtypes(include=np.number).columns
categorical_cols = df.select_dtypes(include=['object']).columns

print(categorical_cols)

print(numeric_cols)

Index(['model_name', 'location'], dtype='str')
Index(['model_year', 'kms_driven', 'owner', 'mileage', 'power', 'price',
       'bike_age'],
      dtype='str')

C:\Users\USER\AppData\Local\Temp\ipykernel_11904\1014761651.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object']).columns

In [19]:
df['brand'] = df['model_name'].apply(lambda x: x.split()[0])

In [20]:
def extract_cc(text):
    # Remove the 4-digit trailing year first to avoid regex conflicts
    text_clean = re.sub(r'\b\d{4}\b$', '', text).strip()
    match = re.search(r'(\d{3})', text_clean)
    return int(match.group(1)) if match else np.nan

df['engine_cc'] = df['model_name'].apply(extract_cc)
df['model_name_cleaned'] = df['model_name'].apply(lambda x: re.sub(r'\b\d{4}\b$', '', x).strip())

In [21]:
df['mileage'] = df['mileage'].fillna(df['mileage'].median())

In [22]:
median_kms = df['kms_driven'].median()
df['kms_driven'] = df['kms_driven'].apply(lambda x: median_kms if x < 100 else x)

In [ ]:
# Resolve Issue 4 & 5: Correct data types and drop multicollinear column
# df['owner'] = df['owner'].astype(int)
df = df.drop(columns=['model_year', 'model_name']) # Drop unneeded raw columns

# --- FEATURE ENGINEERING ---

# Feature 1: Usage intensity (Kilometers driven per year)
df['kms_per_year'] = df['kms_driven'] / df['bike_age']

# Feature 2: Engine power-to-displacement ratio
df['power_to_cc_ratio'] = df['power'] / df['engine_cc']

# Feature 3: Standardize location text formatting
df['location'] = df['location'].str.lower().str.strip()

# Target Feature Transformation (Helps normalize price distribution during ML training)
df['log_price'] = np.log1p(df['price'])

      kms_driven  owner              location  mileage   power    price  bike_age             brand  engine_cc                                               model_name_cleaned  kms_per_year  power_to_cc_ratio  log_price
0        17000.0    1.0             hyderabad     35.0   19.00    63500         9             Bajaj      220.0                                         Bajaj Avenger Cruise 220   1888.888889           0.086364  11.058811
1        50000.0    1.0             hyderabad     35.0   19.80   115000        10             Royal      350.0                                      Royal Enfield Classic 350cc   5000.000000           0.056571  11.652696
2        14795.0    1.0             hyderabad     30.0   28.00   300000        14           Hyosung      250.0                                                   Hyosung GT250R   1056.785714           0.112000  12.611541
3        11000.0    1.0           pondicherry     28.0   34.50   100000         9             Bajaj      400.0                                            Bajaj Dominar 400 ABS   1222.222222           0.086250  11.512935
4         2000.0    1.0             bangalore     40.0   30.00   197500         6              Jawa      330.0                                                 Jawa Perak 330cc    333.333333           0.090909  12.193499
5        24561.0    NaN             bangalore     35.0   25.00    63400        14               KTM      200.0                                                   KTM Duke 200cc   1754.357143           0.125000  11.057235
6        19718.0    1.0             bangalore     65.0   17.00    55000        10             Bajaj      180.0                                               Bajaj Pulsar 180cc   1971.800000           0.094444  10.915107
7        11000.0    1.0             hyderabad     40.0   20.21   120000         6               TVS      200.0                       TVS Apache RTR 200 4V Dual Channel ABS BS6   1833.333333           0.101050  11.695255
8         1350.0    1.0                jaipur     25.0   42.90   198000         8               KTM      390.0                                                   KTM Duke 390cc    168.750000           0.110000  12.196027
9        11000.0    1.0             bangalore     58.0   13.00    40000        12            Yamaha      150.0                                                Yamaha FZ16 150cc    916.666667           0.086667  10.596660
10       25000.0    1.0               chennai     35.0   19.80   136900         8             Royal      350.0                                      Royal Enfield Classic 350cc   3125.000000           0.056571  11.827013
11       26240.0    1.0             ghaziabad     32.0   24.50   112000        10             Royal      410.0                                    Royal Enfield Himalayan 410cc   2624.000000           0.059756  11.626263
12       18866.0    1.0                 delhi     40.0   19.80   110000         9             Royal      350.0                               Royal Enfield Bullet Electra 350cc   2096.222222           0.056571  11.608245
13       11000.0    1.0                 delhi     65.0   10.00    50000         8             Honda      125.0                                             Honda CB Shine 125cc   1375.000000           0.080000  10.819798
14       11000.0    1.0                 delhi     30.0   18.00   131000         7             Royal      350.0                                     Royal Enfield Standard 350cc   1571.428571           0.051429  11.782960
15       11000.0    NaN                 delhi     42.0   23.20    53000         8             Bajaj      200.0                                               Bajaj Pulsar NS200   1375.000000           0.116000  10.878066
16       12634.0    1.0                 delhi     35.0   19.80   160000         7             Royal      350.0                                      Royal Enfield Classic 350cc   1804.857143           0.056571  11.982935
17       11000.0    1.0                 delhi     37.0   19.80   121000        11             Royal      350.0                                     Royal Enfield Standard 350cc   1000.000000           0.056571  11.703554
18       13000.0    1.0                 delhi     37.0   19.80   111000        10             Royal      350.0                                       Royal Enfield Bullet 350cc   1300.000000           0.056571  11.617294
19       28000.0    1.0                 delhi     40.0   19.80   131500         7             Royal      350.0                              Royal Enfield Thunderbird 350cc ABS   4000.000000           0.056571  11.786770
20       11000.0    1.0                 delhi     60.0   14.00    52000        10             Honda      150.0                                           Honda CB Unicorn 150cc   1100.000000           0.093333  10.859018
21       23350.0    1.0                 delhi     37.0   19.00   115000         8             Royal      350.0                                      Royal Enfield Electra 350cc   2918.750000           0.054286  11.652696
22       11000.0    1.0                 delhi     65.0   14.85    47000        12             Bajaj      150.0                                               Bajaj Pulsar 150cc    916.666667           0.099000  10.757924
23        9551.0    1.0                 delhi     53.0   19.00    52000        10             Bajaj      220.0                                         Bajaj Avenger Street 220    955.100000           0.086364  10.859018
24       23522.0    1.0              ludhiana     37.0   19.80   190000         8             Royal      350.0                                       Royal Enfield Bullet 350cc   2940.250000           0.056571  12.154785
25       25000.0    1.0                 delhi     40.0   19.80    67000        11             Royal      350.0                                  Royal Enfield Thunderbird 350cc   2272.727273           0.056571  11.112463
26       12000.0    1.0                 delhi     55.0   12.00    28000        14            Yamaha      150.0                                               Yamaha SZ-RR 150cc    857.142857           0.080000  10.239996
27       10168.0    1.0                 delhi     45.0   13.00    44000        11            Yamaha      150.0                                                 Yamaha FZs 150cc    924.363636           0.086667  10.691968
28        7000.0    1.0                 delhi     35.0   19.80   141500         8             Royal      350.0                                      Royal Enfield Classic 350cc    875.000000           0.056571  11.860062
29       12000.0    1.0                 delhi     35.0   19.80   110000        10             Royal      350.0                                      Royal Enfield Classic 350cc   1200.000000           0.056571  11.608245
30       11000.0    1.0                 delhi     42.0   23.20   118000         6             Bajaj      200.0                                           Bajaj Pulsar NS200 ABS   1833.333333           0.116000  11.678448
31       26683.0    1.0                 delhi     38.0   21.00    65000        10             Bajaj      220.0                                                Bajaj Pulsar 220F   2668.300000           0.095455  11.082158
32        6900.0    1.0             bangalore     35.0   24.80   148000         8                UM        NaN                                      UM Renegade Commando Mojave    862.500000                NaN  11.904974
33       15000.0    1.0               jaunpur   4555.0   13.00    48000         7              Hero      150.0                                              Hero Achiever 150cc   2142.857143           0.086667  10.778977
34       11000.0    1.0                mumbai     58.0   13.00    47475         9            Yamaha      150.0                                          Yamaha FZ S V 2.0 150cc   1222.222222           0.086667  10.767980
35       30202.0    NaN                mumbai     29.0   26.15    58000        15             Honda      250.0                                                   Honda CBR 250R   2013.466667           0.104600  10.968216
36       50000.0    1.0           chittorgarh     55.0    8.90    63000         7              Hero      125.0                                          Hero Glamour Disc 125cc   7142.857143           0.071200  11.050906
37       11000.0    1.0           chittorgarh     65.0   15.00    48000         8             Bajaj      150.0                                               Bajaj Pulsar 150cc   1375.000000           0.100000  10.778977
38       40000.0    1.0           chittorgarh     75.0    9.00    60000         7              Hero      125.0                                        Hero Super Splendor 125cc   5714.285714           0.072000  11.002117
39       20805.0    1.0                 delhi     35.0   19.80    95000        11             Royal      350.0                                      Royal Enfield Classic 350cc   1891.363636           0.056571  11.461643
40       45000.0    1.0           chittorgarh     40.0    8.60    46000         7             Bajaj      110.0                                             Bajaj Discover 110cc   6428.571429           0.078182  10.736418
41       28200.0    1.0             bangalore     38.0   21.00    58000        10             Bajaj      220.0                                                Bajaj Pulsar 220F   2820.000000           0.095455  10.968216
42       50000.0    1.0            thalassery     35.0   19.80    70000        15             Royal      350.0                                      Royal Enfield Classic 350cc   3333.333333           0.056571  11.156265
43       14000.0    1.0             hyderabad     53.0   19.00    55000        10             Bajaj      220.0                                         Bajaj Avenger Street 220   1400.000000           0.086364  10.915107
44       55000.0    1.0           chittorgarh     38.0   21.00    45000        11             Bajaj      220.0                                               Bajaj Pulsar 220cc   5000.000000           0.095455  10.714440
45       30000.0    1.0                 delhi     65.0   17.00    62000         8             Bajaj      180.0                                               Bajaj Pulsar 180cc   3750.000000           0.094444  11.034906
46        1650.0    1.0              bathinda     37.0   19.80   140000         8             Royal      350.0                                       Royal Enfield Bullet 350cc    206.250000           0.056571  11.849405
47       45000.0    1.0             hyderabad     55.0   11.00    30000        12              Hero      125.0                                               Hero Ignitor 125cc   3750.000000           0.088000  10.308986
48       11000.0    1.0               gurgaon     65.0   10.00    51000         7             Honda      125.0                                         Honda CB Shine 125cc CBS   1571.428571           0.080000  10.839601
49       33000.0    1.0                 delhi     40.0   17.00    18000        17              Hero      223.0                                             Hero Karizma R 223cc   1941.176471           0.076233   9.798183
50       27300.0    1.0             hyderabad     40.0   19.80   130000         7             Royal      350.0                                       Royal Enfield Bullet 350cc   3900.000000           0.056571  11.775297
51        5700.0    1.0                mumbai     35.0   24.60   207500         5               KTM      200.0                                             KTM RC 200cc ABS BS6   1140.000000           0.123000  12.242891
52       15000.0    NaN                mumbai     32.0   24.50   181562         7             Royal      410.0                             Royal Enfield Himalayan 410cc Fi ABS   2142.857143           0.059756  12.109358
53       21000.0    1.0              dehradun     25.0   27.20   110000        13             Royal      500.0                                  Royal Enfield Thunderbird 500cc   1615.384615           0.054400  11.608245
54        9000.0    1.0                mumbai     35.0   19.10   207500         6             Royal      350.0                              Royal Enfield Classic 350cc ABS BS6   1500.000000           0.054571  12.242891
55       35000.0    1.0                  pune     63.0   14.00    54468        11            Suzuki      150.0                                              Suzuki Gixxer 150cc   3181.818182           0.093333  10.905387
56       11000.0    1.0            kukatpally     65.0   10.00    70000         8             Honda      125.0                                      Honda CB ShineSP 125cc Disc   1375.000000           0.080000  11.156265
57       20864.0    1.0                 delhi     38.0   21.00    55000         9             Bajaj      220.0                                               Bajaj Pulsar 220cc   2318.222222           0.095455  10.915107
58       11000.0    1.0                  pune     65.0   14.85    30087        18             Bajaj      150.0                                               Bajaj Pulsar 150cc    611.111111           0.099000  10.311882
59       44228.0    1.0           chittorgarh     55.0    8.00    57000         7              Hero      110.0                                          Hero Passion Xpro 110cc   6318.285714           0.072727  10.950824
60       11000.0    1.0             bangalore     28.0   34.50   150000         9             Bajaj      400.0                                                Bajaj Dominar 400   1222.222222           0.086250  11.918397
61        7000.0    1.0                mumbai   3185.0   29.63   197125         6         Husqvarna      250.0                                         Husqvarna Svartpilen 250   1166.666667           0.118520  12.191598
62        9000.0    1.0                mumbai     40.0   19.80   166000         7             Royal      350.0                            Royal Enfield Thunderbird X 350cc ABS   1285.714286           0.056571  12.019749
63       21500.0    1.0             hyderabad     40.0   16.10    93000         7               TVS      160.0                                   TVS Apache RTR 160 4V DISC ABS   3071.428571           0.100625  11.440366
64       11000.0    NaN             hyderabad     40.0   20.23    88000         8               TVS      200.0                                        TVS Apache RTR 200 4V ABS   1375.000000           0.101150  11.385103
65        7714.0    1.0                 delhi     40.0   19.80   135000         7             Royal      350.0                               Royal Enfield Bullet Electra 350cc   1102.000000           0.056571  11.813037
66       60000.0    1.0                 delhi     45.0   13.00    32000        14            Yamaha      150.0                                                 Yamaha FZs 150cc   4285.714286           0.086667  10.373522
67        5389.0    1.0                 delhi     35.0   19.80   165000         6             Royal      350.0                                  Royal Enfield Classic 350 S ABS    898.166667           0.056571  12.013707
68        9500.0    1.0             hyderabad     40.0   26.10   120000         7            Suzuki      250.0                                       Suzuki Gixxer SF 250cc ABS   1357.142857           0.104400  11.695255
69       12573.0    1.0                 delhi     40.0   18.70   128000         7            Yamaha      150.0                                          Yamaha YZF-R15 V3 150cc   1796.142857           0.124667  11.759793
70       34000.0    1.0           chittorgarh   4555.0    7.00    45000         9              Hero        NaN                             Hero Splendor ISmart Self Drum Alloy   3777.777778                NaN  10.714440
71       28240.0    1.0           chittorgarh     40.0    9.30    50000         7              Hero      110.0                                      Hero Passion Pro 110cc Drum   4034.285714           0.084545  10.819798
72       30000.0    1.0           chittorgarh      5.0    8.20    42000         8              Hero      100.0                                Hero Passion Pro 100cc Drum Alloy   3750.000000           0.082000  10.645449
73       38000.0    NaN              dehradun     38.0   21.00    30000        16             Bajaj      220.0                                               Bajaj Pulsar 220cc   2375.000000           0.095455  10.308986
74        9563.0    NaN           navi mumbai     45.0   14.30    39000         9             Bajaj      150.0                                         Bajaj Avenger Street 150   1062.555556           0.095333  10.571343
75       23000.0    1.0               lucknow     40.0   26.10    70000         7            Suzuki      250.0                                              Suzuki Gixxer 250cc   3285.714286           0.104400  11.156265
76       67000.0    1.0                 delhi      5.0    8.20    26000        15              Hero      100.0                                           Hero Passion Pro 100cc   4466.666667           0.082000  10.165890
77       56194.0    1.0                 delhi      5.0    8.20    20000        15              Hero      100.0                                           Hero Passion Pro 100cc   3746.266667           0.082000   9.903538
78       11000.0    1.0                  pune     65.0   14.85    40000        12             Bajaj      150.0                                               Bajaj Pulsar 150cc    916.666667           0.099000  10.596660
79       27000.0    NaN             hyderabad     45.0   13.00    48500        12            Yamaha      150.0                                                 Yamaha FZs 150cc   2250.000000           0.086667  10.789340
80       37788.0    1.0              siliguri     50.0   11.90    43000        13            Yamaha      150.0                                         Yamaha SZ RR V 2.0 150cc   2906.769231           0.079333  10.668979
81       11000.0    1.0             bengaluru     45.0   17.20    80000         9               TVS      180.0                                             TVS Apache RTR 180cc   1222.222222           0.095556  11.289794
82       11000.0    1.0                 delhi     35.0   24.50   110000         8             Bajaj      200.0                                               Bajaj Pulsar RS200   1375.000000           0.122500  11.608245
83       11000.0    1.0                  pune     35.0   24.16    76300        11             Bajaj      200.0                                               Bajaj Pulsar RS200   1000.000000           0.120800  11.242441
84        5700.0    1.0               gurgaon     40.0   18.70   117500         7            Yamaha      150.0                                      Yamaha YZF-R15 V3 150CC ABS    814.285714           0.124667  11.674202
85       19000.0    1.0                rajkot     40.0   18.70   125000         7            Yamaha      150.0                                      Yamaha YZF-R15 V3 150CC ABS   2714.285714           0.124667  11.736077
86       23000.0    1.0             bangalore     35.0   19.80   114500        12             Royal      350.0                                      Royal Enfield Classic 350cc   1916.666667           0.056571  11.648339
87       11000.0    1.0                  agra     35.0   24.50   100000         8             Bajaj      200.0                                           Bajaj Pulsar RS200 ABS   1375.000000           0.122500  11.512935
88       11000.0    1.0              bhiwandi     35.0   24.50   115000         9             Bajaj      200.0                                           Bajaj Pulsar RS200 ABS   1222.222222           0.122500  11.652696

In [44]:
df.isnull().sum()

kms_driven               3
owner                 1040
location                19
mileage                  0
power                   31
price                    0
bike_age                 0
brand                    0
engine_cc              261
model_name_cleaned       0
kms_per_year             3
power_to_cc_ratio      286
log_price                0
dtype: int64

In [46]:
df_clean = df.dropna()
df_clean.isnull().sum()

kms_driven            0
owner                 0
location              0
mileage               0
power                 0
price                 0
bike_age              0
brand                 0
engine_cc             0
model_name_cleaned    0
kms_per_year          0
power_to_cc_ratio     0
log_price             0
dtype: int64

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
# Algorithms to test
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor, HistGradientBoostingRegressor

In [47]:
X = df_clean.drop(columns=['price'])
y = np.log1p(df_clean['price'])

In [48]:
# 3. Define feature groups for preprocessing
num_features = ['kms_driven', 'mileage', 'power', 'bike_age', 'engine_cc', 'kms_per_year', 'power_to_cc_ratio', 'owner']
cat_features = ['location', 'brand']

In [49]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_features),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_features)
    ]
)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [50]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [51]:
models = {
    "Linear Regression": LinearRegression(),
    "Ridge Regression": Ridge(alpha=1.0),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "Gradient Boosting": HistGradientBoostingRegressor(random_state=42)
}

In [52]:
X_train_proc = preprocessor.fit_transform(X_train)
X_test_proc = preprocessor.transform(X_test)

In [53]:
results = []

for name, model in models.items():
    # Train
    model.fit(X_train_proc, y_train)
    
    # Predict & Convert back from log-scale to true currency
    y_pred_log = model.predict(X_test_proc)
    y_pred_actual = np.expm1(y_pred_log)
    y_test_actual = np.expm1(y_test)
    
    # Calculate Evaluative Metrics
    mse = mean_squared_error(y_test_actual, y_pred_actual)
    mae = mean_absolute_error(y_test_actual, y_pred_actual)
    r2 = r2_score(y_test_actual, y_pred_actual)
    
    results.append({
        "Model": name,
        "Mean Absolute Error (MAE)": f"${mae:,.2f}",
        "R² Score": f"{r2:.4f}"
    })

# Output Comparison Table
results_df = pd.DataFrame(results)
print(results_df.to_string(index=False))

            Model Mean Absolute Error (MAE) R² Score
Linear Regression                $25,776.43   0.1795
 Ridge Regression                $25,431.55   0.1899
    Random Forest                $14,051.18   0.8968
Gradient Boosting                $15,257.40   0.8937