In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_test = pd.read_csv('test.csv')
df_train = pd.read_csv('train.csv')

In [3]:
df_train.head()

,Date,Region,Brand,Model,Vehicle_Type,Battery_Capacity_kWh,Discount_Percentage,Customer_Segment,Fast_Charging_Option,Units_Sold
0,2024-07,Oceania,Toyota,i4,Crossover,60.084153,6.025559,High Income,No,133.340719
1,2024-03,Oceania,Toyota,Leaf,Truck,67.058251,18.953440,High Income,Yes,155.244623
2,2024-05,North America,Toyota,ID.5,Crossover,84.031469,13.006385,Middle Income,No,155.790594
3,2024-02,Oceania,Tesla,Corolla EV,Truck,73.646300,3.854783,High Income,Yes,130.724024
4,2024-10,North America,BYD,Leaf,Coupe,49.498818,4.082615,High Income,No,120.654082

In [4]:
df_test.head()

,Date,Region,Brand,Model,Vehicle_Type,Battery_Capacity_kWh,Discount_Percentage,Customer_Segment,Fast_Charging_Option
0,2023-04,Oceania,Volkswagen,Model 3,SUV,45,16,Budget Conscious,No
1,2023-10,Oceania,Ford,Model 3,Sedan,89,5,Tech Enthusiast,Yes
2,2023-10,South America,Volkswagen,Atto 3,Sedan,61,4,Budget Conscious,Yes
3,2023-02,Africa,Volkswagen,Corolla EV,Crossover,100,16,Eco-Conscious,No
4,2023-10,North America,Tesla,Rio EV,Sedan,70,8,Eco-Conscious,Yes

In [5]:
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  275 non-null    str
 1   Region                275 non-null    str
 2   Brand                 275 non-null    str
 3   Model                 275 non-null    str
 4   Vehicle_Type          275 non-null    str
 5   Battery_Capacity_kWh  275 non-null    int64
 6   Discount_Percentage   275 non-null    int64
 7   Customer_Segment      275 non-null    str
 8   Fast_Charging_Option  275 non-null    str
dtypes: int64(2), str(7)
memory usage: 19.5 KB

In [7]:
df_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  531 non-null    str
 1   Region                531 non-null    str
 2   Brand                 531 non-null    str
 3   Model                 531 non-null    str
 4   Vehicle_Type          531 non-null    str
 5   Battery_Capacity_kWh  531 non-null    float64
 6   Discount_Percentage   531 non-null    float64
 7   Customer_Segment      531 non-null    str
 8   Fast_Charging_Option  531 non-null    str
 9   Units_Sold            531 non-null    float64
dtypes: float64(3), str(7)
memory usage: 41.6 KB